# 5 Numpy Functions which is usefull for Every Data Analyst and Every Data Analyst Should Know with Practical Examples

## What is Numpy?
**NumPy is a Python library for working with large, multi-dimensional arrays and matrices of numerical data. It provides a high-performance multidimensional array object, and tools for working with these arrays. NumPy is an essential library for scientific computing with Python, and is widely used in many scientific, engineering, and data analysis applications.**

**NumPy arrays are used to store and manipulate large arrays of homogeneous numerical data (i.e., data of the same type, such as integers or floating point values). NumPy arrays are more efficient and more convenient to use than Python's built-in list or tuple objects, because they allow you to perform element-wise operations (e.g., addition, multiplication, etc.) on the entire array, rather than having to loop over the elements of the array yourself. NumPy also provides a large number of functions for performing mathematical operations on arrays, such as linear algebra functions, statistical functions, and other types of numerical operations.**

**In addition to its array object, NumPy also provides functions for reading and writing arrays to and from files, and tools for integrating NumPy with other scientific libraries like SciPy and Matplotlib.**






In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

# List of functions explained 
- function 1 = np.linalg.solve
- function 2 = np.place
- function 3 = np.clip
- function 4 = np.copyto
- function 5 = np.stack

## Function 1 - np.linalg.solve
This function falls under the category of linear algebric function. Generally we have to solve liner equations to get the required value. By using this function, we can solve the equations and solve the problems.

In [2]:
import numpy as np

In [3]:
# Example 1 - working 
a = np.array([[6, 8], 
        [9, 6]])

b = np.array([7, 14])

x=np.linalg.solve(a,b)
x

array([ 1.94444444, -0.58333333])

This is the example of linear system of equations of two variables.So we get two values as a solution.that means that gives the solution of linear equations in the matrix form.

In [4]:
# Example 2 - working
c=np.array([[7,6,9],[4,96,4],[12,75,15]])

d=np.array([16,18,14])

y=np.linalg.solve(c,d)

y

array([ 70.875     ,  -0.55833333, -52.975     ])

This is the example of linear system of equations of three variables.In this case we get the three solutions.

In [5]:
# Example 3 - breaking 
e =np.array ([[14, 2,8], 
              [13, 24,87],
             [50,70,90]])

f=np.array([40,64])

x=np.linalg.solve(e,f)
x

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 2 is different from 3)

n this example the number of constant are not equal to the number of system of equations. Thats why this does not work. In order to run it correctly, we have to make the number of constant equal to the number of system of equations.

This function is used generally to solve the system of linear equations. It is a common mathematical operation and reduce the time of operating in calculator.



In [6]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "nikpatel6596/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/nikpatel6596/numpy-array-operations


'https://jovian.ai/nikpatel6596/numpy-array-operations'

## Function 2 - np.place
NumPy's `np.place` function is a tool for placing the elements of one array into the specified locations of another array. It allows you to specify the positions at which the elements of the first array should be placed, and the values of the second array at those positions will be replaced with the corresponding elements of the first array.

Here is an example of how np.place can be used:

In [34]:
# Example 1 - working
import numpy as np

p=np.array([[8,9],
          [10,11]])

np.place(p,p==8,10)

p

array([[10,  9],
       [10, 11]])

In this example we create a array, then we like to replace the elements of array with some specific element. So we put a condition in which if the element of array is equal to 8 it would be replaced by number 10.

In [12]:
# Example 2 - working

x=np.arange(9).reshape(3,3)

np.place(x,x>3,[33,22])
x

array([[ 0,  1,  2],
       [ 3, 33, 22],
       [33, 22, 33]])

It is a little bit of advaned form of previous example. In this example we create a (3,3) array then put on a condition in which if number is greater than 2, it would be replaced by the series of number 33 and 22 one after another.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
x=np.arange(9).reshape(3,3,3)

np.place(x,x>3,[33,22])
x

ValueError: cannot reshape array of size 9 into shape (3,3,3)

Mismatched shapes: If the shape of the array being modified (the first argument to np.place) does not match the shape of the values array, an IndexError will be raised. Make sure that the shapes of these arrays match, or use a compatible indexing scheme 

## Function 3 - ???

NumPy's `np.clip` function is used to clip (limit) the values of an array to a given range. It allows you to specify a minimum and maximum value, and all values in the array that are less than the minimum will be replaced with the minimum, and all values that are greater than the maximum will be replaced with the maximum. The values between the minimum and maximum are left unchanged.

Here is an example of how np.clip can be used:

In [20]:
# Example 1 - working
a = np.random.randint(-10, 10, size=(5, 5))

b = np.clip(a, -5, 5)

print(a)
print(b)

[[ -9   7  -9   5  -4]
 [ -4  -9   1   3  -9]
 [ -3 -10  -6  -3   3]
 [  8   0  -9  -7  -5]
 [ -7   8   9  -9   0]]
[[-5  5 -5  5 -4]
 [-4 -5  1  3 -5]
 [-3 -5 -5 -3  3]
 [ 5  0 -5 -5 -5]
 [-5  5  5 -5  0]]


In this example, a is an array of random values between -10 and 10, and b is the result of clipping the values in a to the range [-5, 5]. All values in a that are less than -5 are replaced with -5 in b, and all values in a that are greater than 5 are replaced with 5 in b. The values between -5 and 5 are left unchanged.

In [23]:
# Example 2 - working
a = np.random.randint(-10, 10, size=(5, 5))

b = np.clip(a, -5, None)

print(b)

[[ 1  2 -3  9  4]
 [-2 -5 -2  4  6]
 [-5  2  0  3 -5]
 [ 5  7  4  0 -5]
 [-5  0  7 -5 -5]]


You can also specify only one of the minimum or maximum values, in which case only the values below or above the specified value will be replaced

In this example, b is the result of clipping the values in a to the range [-5, inf], so only the values less than -5 are replaced with -5.

`np.clip` is a useful function for preprocessing data and ensuring that all values fall within a given range. It is often used in machine learning and data analysis applications to ensure that data is within a valid range for further processing or analysis.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.random.randint(-10, 10, size=(5, 5))

b = np.clip(a, '-5', '5')
print(a)
print(b)
    
    

UFuncTypeError: ufunc 'clip' did not contain a loop with signature matching types (dtype('int64'), dtype('<U2'), dtype('<U1')) -> None

In this example, the minimum and maximum values are specified as strings, rather than numeric values. This will cause a TypeError to be raised when np.clip is called, because the dtype of the minimum and maximum values is not compatible with the dtype of the array being clipped.

To fix this error, you would need to either convert the minimum and maximum values to a numeric dtype (such as int or float), or use a dtype casting function (such as np.asarray) to convert the array to a dtype that is compatible with the string values.

## Function 4 - np.copyto

NumPy's `np.copyto` function is a tool for copying values from one array to another. It allows you to specify the source array (the array from which the values will be copied) and the destination array (the array to which the values will be copied), and the values in the source array will be copied to the corresponding positions in the destination array.



In [26]:
# Example 1 - working
a = np.random.randint(0, 10, size=(5, 5))

b = np.empty_like(a)

np.copyto(b, a)

print(a)
print(b)

[[0 9 5 4 8]
 [5 3 3 3 4]
 [8 9 5 1 5]
 [8 1 3 6 5]
 [6 9 1 0 3]]
[[0 9 5 4 8]
 [5 3 3 3 4]
 [8 9 5 1 5]
 [8 1 3 6 5]
 [6 9 1 0 3]]


n this example, a is an array of random values, and b is an empty array with the same shape as a. The values in a are then copied to b using np.copyto, so that b contains the same values as a.

`np.copyto` is a useful function for creating copies of arrays, or for transferring values between arrays. It is often used in scientific computing and data analysis applications to create copies of data for further processing or analysis.

In [27]:
# Example 2 - working

a = np.array([6, 5, 11]) 
b = [9, 10, 11] 

np.copyto(a, b)

print(a)
         

[ 9 10 11]


In this example, the values of the b list are copied to the a array using np.copyto. The a array is then modified in place, so that its values are set to the copied values.

The reason this code works is because the b list can be automatically converted to a NumPy array before the values are copied. This is known as "implicit casting" and is a feature of NumPy that allows you to pass lists or other sequences to NumPy functions that expect arrays as input.

When you pass a list to np.copyto, NumPy will automatically convert the list to a NumPy array using the np.asarray function. The values of the b list are then copied to the a array using np.copyto, and the a array is modified in place to contain the copied values.

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.zeros((3, 3))

b = np.zeros((2, 2))

np.copyto(a, b)

ValueError: could not broadcast input array from shape (2,2) into shape (3,3)

In this example, the a array has shape (3, 3), while the b array has shape (2, 2). This means that the shapes of a and b do not match, and an ValueError will be raised when np.copyto is called.

To fix this error, you would need to either change the shape of the b array so that it matches the shape of a, or use a compatible indexing method (such as boolean indexing) to specify the locations to copy the values.

## function 5 = np.stack

NumPy's `np.stack` function is used to stack arrays along a new axis. It allows you to combine multiple arrays into a single array, by concatenating them along a new axis.

Here is an example of how np.stack can be used:

In [30]:
# Example 1 - working

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

d = np.stack([a, b, c])

print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In this example, the a, b, and c arrays are stacked along a new axis to form a new array d with shape (3, 3). The resulting d array contains the values of the a, b, and c arrays, with the original arrays being concatenated along the new axis.

In [31]:
# Example 2 - working

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.stack((a, b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


In this example Along this axis, in the new array, input arrays are stacked. Possible values are 0 to (n-1) positive integer for n-dimensional output array. For example, in the case of a resultant 2-D array, there are 2 possible axis options :0 and 1. axis=0 means 1D input arrays will be stacked row-wise. axis=1 means 1D input arrays will be stacked column-wise.

In [32]:
#Example 3 - breaking (to illustrate when it breaks)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8])

d = np.stack([a, b, c])

ValueError: all input arrays must have the same shape

In this example, the a, b, and c arrays have different shapes, so np.stack will raise a ValueError. This is because np.stack requires that the input arrays have the same shape, so that they can be concatenated along the new axis.

To fix this error, you would need to either ensure that the input arrays have the same shape, or use a compatible indexing method (such as boolean indexing) to specify the locations to stack the values.

# Conclusion

NumPy is a powerful library for scientific computing and data analysis in Python. It provides a wide range of functions and features that allow you to work with arrays and matrices of numerical data, including tools for indexing, reshaping, and manipulating arrays, as well as functions for performing mathematical operations on arrays.

Some of the key features and functions of NumPy include:

* array: A flexible, multi-dimensional array that can hold any type of data. NumPy's ndarray is used to store and manipulate large arrays of numerical data efficiently.

* Array indexing: NumPy provides several methods for indexing and selecting elements from arrays, including integer indexing, boolean indexing, and slicing.

* Array reshaping: NumPy's reshape function allows you to change the shape of an array, while the ravel function flattens an array into a 1D array.

* Array manipulation: NumPy provides functions for rotating, flipping, and transposing arrays, as well as functions for sorting and searching arrays.

* Mathematical operations: NumPy provides a wide range of functions for performing mathematical operations on arrays, including functions for basic arithmetic, trigonometry, and linear algebra.

Overall, NumPy is an essential tool for anyone working with numerical data in Python, and is widely used in scientific computing and data analysis applications.

# Reference Links
Provide links to your references and other interesting articles about Numpy arrays:

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy Reference:https://numpy.org/doc/stable/reference/index.html

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "nikpatel6596/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/nikpatel6596/numpy-array-operations


'https://jovian.ai/nikpatel6596/numpy-array-operations'